[features]
seeds = false
skip-lint = false

[programs.localnet]
campus_voice = "2h198Q9MNSFGWo2aJeEq2CRFSSfykfFVKUkbDJhyzrAf"

[programs.devnet]
campus_voice = "2h198Q9MNSFGWo2aJeEq2CRFSSfykfFVKUkbDJhyzrAf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
